Traceback (most recent call last):
  File "/home/skyr/.local/share/JetBrains/Toolbox/apps/pycharm-professional/plugins/python/helpers/pydev/pydevd.py", line 1551, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skyr/.local/share/JetBrains/Toolbox/apps/pycharm-professional/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/skyr/PycharmProjects/MuAlphaZeroBuild/connect4mz/train_mz.py", line 170, in <module>
    train_mz()
  File "/home/skyr/PycharmProjects/MuAlphaZeroBuild/connect4mz/train_mz.py", line 70, in train_mz
    mz.train()
  File "/home/skyr/PycharmProjects/MuAlphaZeroBuild/mu_alpha_zero/MuZero/muzero.py", line 98, in train
    self.trainer.train()
  File "/home/skyr/PycharmProjects/MuAlphaZeroBuild/mu_alpha_zero/trainer.py", line 153, in train
    mean_loss, losses = self.network.train_net(self.memory, self.muzero_alphazero_config)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skyr/PycharmProjects/MuAlphaZeroBuild/mu_alpha_zero/MuZero/Network/networks.py", line 123, in train_net
    loss, loss_v, loss_pi, loss_r = self.calculate_losses(sampled_game_data, weights, device, muzero_config)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skyr/PycharmProjects/MuAlphaZeroBuild/mu_alpha_zero/MuZero/Network/networks.py", line 186, in calculate_losses
    loss *= th.tensor(weights, dtype=loss.dtype, device=loss.device)
RuntimeError: output with shape [] doesn't match the broadcast shape [3]